version: "3.8"

services:
  web:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    depends_on: []
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
